// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:1cb26b97-d5e9-406c-a98d-8c1f4638efe6',
    'aws_cognito_region': 'eu-west-1',
    'aws_mobile_analytics_app_id': 'f4578d3c7c6241fd9a78fb4dc7cb7b02',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5ce7bb9f-39d0-433a-8de3-5cc327e10842',
    'aws_project_name': 'Recipe Demo',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'recipedemo-mobilehub-240842941',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-1_4k8eGPoqS',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '65eomqgcfpv400igoot61rctpm',
}

export default awsmobile;
